arb-dir: lib/core/l10n/arb
template-arb-file: app_tr.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/core/l10n/gen
synthetic-package: false
nullable-getter: false
